FROM dotnet-20-rhel7:latest
# This image provides a .NET Core 2.0 environment you can use to run your .NET
# applications.

USER 0

RUN chmod a+rwx /etc/hosts && echo "api.news.gov.bc.ca  142.34.142.141" > /etc/hosts


USER 1001

